#Postgre Configuration
spring.datasource.url=jdbc:postgresql://dpg-d4gaf4m3jp1c73fjmff0-a.singapore-postgres.render.com/moneymanager_n7vq
spring.datasource.username=moneymanager_n7vq_user
spring.datasource.password=Xs6THZL5lSAyke0K6jmfmH7p3zWmovuv