#Postgre Configuration
spring.datasource.url=jdbc:postgresql://moneymanager_new_user:0vSMVjvS8Lun1YFMxSOOLrMpSwJksz3d@dpg-d544tuqli9vc73agutm0-a.singapore-postgres.render.com/moneymanager_new
spring.datasource.username=moneymanager_new_user
spring.datasource.password=0vSMVjvS8Lun1YFMxSOOLrMpSwJksz3d